package cards;
//MI CHIEDO SE HA SENSO SEPARARLO DAGLI OGGETTI O TENERE TUTTO IN SIMBOLI

public enum Resources {
		PLANT_KINGDOM,
		ANIMAL_KINGDOM,
		FUNGI_KINGDOM,
		INSECT_KINGDOM,
		EMPTY,
		NULL
}
